version: '3.8'

services:
  postgres:
    build: ./postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: paypay
      POSTGRES_PASSWORD: paypay_password
      POSTGRES_DB: paypay_investment_helper
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paypay"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://paypay:paypay_password@postgres:5432/paypay_investment_helper
      BACKEND_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  analysis:
    build: ./analysis
    environment:
      BACKEND_URL: http://backend:3000
      PYTHONPATH: /app
    ports:
      - "5000:5000"
    depends_on:
      - backend
    command: python -m src

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend

volumes:
  postgres_data: